version: '3'

services:
  garbage-collection:
    image: garbage-collection
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - /root/uploaded-files:/app/data
    networks:
      - bighut_lk_network

networks:
  bighut_lk_network:
    external:
      name: bighut_lk_network
